// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv7VTSnTu2dCmysWIC4QKR3sj_SYFv4MU',
    appId: '1:644254828592:web:8ff69f98b80f4abbe505f5',
    messagingSenderId: '644254828592',
    projectId: 'fabchain-ee17b',
    authDomain: 'fabchain-ee17b.firebaseapp.com',
    storageBucket: 'fabchain-ee17b.firebasestorage.app',
    measurementId: 'G-9TT4C26SRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6vsVgUetw5fiuLSxFKky550oc9Lrs7Mc',
    appId: '1:644254828592:android:e30a1a4589089698e505f5',
    messagingSenderId: '644254828592',
    projectId: 'fabchain-ee17b',
    storageBucket: 'fabchain-ee17b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW-50d-CNi4X34uxxHV4vszEx6VLyk17A',
    appId: '1:644254828592:ios:6b3f7522a4df7d65e505f5',
    messagingSenderId: '644254828592',
    projectId: 'fabchain-ee17b',
    storageBucket: 'fabchain-ee17b.firebasestorage.app',
    iosBundleId: 'com.example.appFabchain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW-50d-CNi4X34uxxHV4vszEx6VLyk17A',
    appId: '1:644254828592:ios:6b3f7522a4df7d65e505f5',
    messagingSenderId: '644254828592',
    projectId: 'fabchain-ee17b',
    storageBucket: 'fabchain-ee17b.firebasestorage.app',
    iosBundleId: 'com.example.appFabchain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv7VTSnTu2dCmysWIC4QKR3sj_SYFv4MU',
    appId: '1:644254828592:web:496147ed486dc3c9e505f5',
    messagingSenderId: '644254828592',
    projectId: 'fabchain-ee17b',
    authDomain: 'fabchain-ee17b.firebaseapp.com',
    storageBucket: 'fabchain-ee17b.firebasestorage.app',
    measurementId: 'G-MKRK3EER5Z',
  );
}
